apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
      type: frontend
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        type: app1
      
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: app1
